### ISSUE TITLE
При смене ориентации экрана во время ввода данных происходит возврат на экран ввода точки, без сохранения данных

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/tree_mapper#10]

**Comment by Kinda-me** [comment]
Теперь при смене ориентации экрана приложение сворачивается в фон

**Comment by 4eRTuk** [comment]
Подозреваю что проблема также в MIUI. Я поправил краш, но он был на основном экране при повороте.

**Comment by Kinda-me** [comment]
У Максима на Sony то же самое.

**Comment by 4eRTuk** [comment]
Опиши полностью юзкейс плиз.

**Comment by Kinda-me** [comment]
Если на главном экране сменить ориентацию, то приложение сворачивается в фон. Вроде это весь юзкейс. На других экранах такого не отловила.

**Comment by 4eRTuk** [comment]
Не тот тикет) Там крэш, а не сворачивание в фон. У тебя видимо не показываются уведомление о падении. Починено.
