### ISSUE TITLE
Ошибки на экране отображения информации о созданном объекте 

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/tree_mapper#11]
1. Не отображаются прикрепленные к объкту фото.
2. Список отображаемых атрибутов не соответствует списку заполняемых атрибутов.

**Comment by BishopGIS** [comment]
Вообще надо как в дизайне - http://176.9.38.120/woody/site/android.tree_mapper/art/design/
В дереве слева в самом низу см п 7. Edit

**Comment by Kinda-me** [comment]
3. Не влезает целиком заголовок (название дерева) - мешают кнопки удаления-редактирования.

**Comment by Kinda-me** [comment]
Название дерева по-прежнему не влезает.

![screenshot_2017-11-02-11-24-24-734_com nextgis woody](https://user-images.githubusercontent.com/6493848/32318591-c6a4645a-bfc8-11e7-95f6-1a764fc0ce95.png)

**Comment by BishopGIS** [comment]
Наверное стоит сделать тут 2 строки текста

**Comment by Kinda-me** [comment]
Вот так у Максима на телефоне, если не приаттачивать фоточку:

![photo_2017-11-02_12-36-31](https://user-images.githubusercontent.com/6493848/32319140-898f46d2-bfca-11e7-9976-a0de8692397e.jpg)
