### ISSUE TITLE
Не работает синхронизация с сервером

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/tree_mapper#12]
Точка, созданная в мобильном приложении, спустя сутки так и не появилась здесь - http://176.9.38.120/woody/site/web/

**Comment by BishopGIS** [comment]
Наверное надо sentry подключить что бы перехватывать событие синхронизации.

**Comment by 4eRTuk** [comment]
Аня, проверь еще раз. Сначала только удали приложение и еще аккаунт из настроек Андроида.

**Comment by Kinda-me** [comment]
Все сделала, прошло больше часа - точки пока не появились в вебе.

**Comment by 4eRTuk** [comment]
А у тебя еще есть какие-нибудь наши приложения установленные?

**Comment by Kinda-me** [comment]
Да, Mobile.

**Comment by 4eRTuk** [comment]
А какая сборка? Тестовая или из маркета?

**Comment by Kinda-me** [comment]
Из маркета

**Comment by BishopGIS** [comment]
От заказчика тоже пришло сообщение о не рабочей синхронизации. Пердлагаю добавить кнопку принудительной синхронизации и на этом закрыть тикет.

**Comment by BishopGIS** [comment]
Для инфо - аппарат на котором не работает синхронизация - Мегафон Оптима
