### ISSUE TITLE
Тайлы грузятся очень медленно

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/tree_mapper#14]
Даже те, что по идее должны были закэшироваться.

**Comment by BishopGIS** [comment]
@4eRTuk там не могло быть, что старые библиотеки как-то подцепились? Версии увеличивались что бы проверить?
Посмотрел - АПИ 28 (2.5.6.5)

**Comment by 4eRTuk** [comment]
Нет, я обновлял. На симуляторе быстро довольно.

**Comment by BishopGIS** [comment]
Я вспомнил - у @Kinda-me же 6-й Андроид! Там все в один поток.

**Comment by Kinda-me** [comment]
Да, у меня 6 андроид, у меня все в один поток. Вроде как-то решали уже эту проблему?

**Comment by BishopGIS** [comment]
На 6-ке в несколько потоков падает. Причем только на 6-ке. 5, 7 и далее - нет такой проблемы. Поэтому там простое решение - если 6-ка все в один поток, на другой версии ОС в несколько. В новой библиотеке (v3) такой проблемы не будет.
