### ISSUE TITLE
Применение кнопки "Определить мое местоположение" на экране "Точка на карте" не перемещает точку в определенное местоположение

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/tree_mapper#16]
При этом приложение даёт пройти все остальные шаги после этого, нажать кнпоку "Готово", и в итоге дерево не создается.

**Comment by Kinda-me** [comment]
Попробовала создать еще несколько деревьев без использования этой кнопки - ни одно не создалось. Возможно точка не удаляется, а остается на прежнем месте, а деревья не создаются по иной причине.

**Comment by Kinda-me** [comment]
Подтверждаю, в новой сборке точка остается в прежнем месте.

**Comment by 4eRTuk** [comment]
А должно именно точку перемещать? Тогда нужно отдельную кнопку какую-то - обычно центрирование карты по кнопке с геолокацией.

**Comment by Kinda-me** [comment]
Возможно и не должно.

**Comment by 4eRTuk** [comment]
@BishopGIS  Как сделать?

**Comment by Kinda-me** [comment]
Как вариант - с кнопкой этой все оставить как есть. Но экстент карты на экране создания точки по умолчанию центрировать на текущем местоположении.

**Comment by BishopGIS** [comment]
Идея была что пользователь сам двигает точку дерева. Никакого функционала по перемещению точки в координаты не предусматривалось. Мне кажется вариант @Kinda-me подходящий - центрирование в текущем местоположении и точка в центре экрана что бы можно было двигать.

**Comment by 4eRTuk** [comment]
то есть при открытии экрана нового дерева центрирование на текущем местоположении и точка по центру? при клике на кнопку просто центрирование?

**Comment by BishopGIS** [comment]
Да
