### ISSUE TITLE
Ошибки во вкладке "Параметры для экспертов"

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/tree_mapper#17]
1. Значение "Обхват ствола" передается неверно (задаю значение, но на экране просмотра данных выводится 0.0).
2. При редактировании параметров ранее введенные в этой вкладке параметры - не отображаются.
3. После редактирования параметров новые параметры отображаются на экране просмотра данных только если закрыть и открыть его снова.
4. Поля "Начало формирования кроны" и "Повреждения" предлагается заполнить с использованием только цифровой клавиатуры - это правильно?

**Comment by 4eRTuk** [comment]
Fix in df24bad84d86d237403eff37560e8031e4d01717
