### ISSUE TITLE
"Ошибка инициализации" при регистрации через FB

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/tree_mapper#5]
Все данные ввела, разрешения предоставила, нажала ОК - получила "Ошибка инициализации". Закрыла приложение, открыла по-новой - запустился процесс загрузки данных.

**Comment by 4eRTuk** [comment]
Можешь подробнее написать? Куда ты ввела данные и где ок нажала?

**Comment by 4eRTuk** [comment]
А, понял. Это если НГВ аккаунт уже есть на телефоне.

**Comment by BishopGIS** [comment]
От заказчика:
```
Я установила приложение на планшете, оно установилось, но при 
входе требует регистрации в фэйсбуке или контакте. Я нажимаю значок ФБ - 
усройство пишет "ошибка инициализации".
```

**Comment by 4eRTuk** [comment]
Что-то никак не могу поймать. Пусть попробует зайти в Настройки Android > Аккаунты > NextGIS > Удалить Вуди и еще раз авторизоваться.

**Comment by BishopGIS** [comment]
Ты можешь отладку в сентри добавить? Потому что я в админке вижу, что пользователь аж 5 раз создался именно через соц. сети - возможно дело в другом. Сентри же все равное уже в приложение интегрирована.

**Comment by BishopGIS** [comment]
Еще информация - аккаунта на устройстве не было. Такое может быть, что на сервере создался аккаунт, а потом на устройстве не пришел код возврата или пришел код ошибки и аккаунт не создался?

**Comment by BishopGIS** [comment]
Теперь вот так выглядит:
![23593739_1272456922860024_5622979161532680137_o](https://user-images.githubusercontent.com/1708122/32721820-d8dea7bc-c878-11e7-8b76-e2f4c35b309b.jpg)
