### ISSUE TITLE
Кнопка "Стрелка" на всех экранах ввода данных выкидывает на основной экран, без сохранения данных

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/tree_mapper#7]
Лучше сделать так, чтобы она соответствовала кнопке "Назад" в нижней части экрана и перекидывала на предыдущий шаг.

**Comment by 4eRTuk** [comment]
Это не очень то соответствует гайдлайнам Google. По софт (хард) кнопке назад надо бы так делать.

**Comment by BishopGIS** [comment]
Текущее поведение вообще не соответсвует гайдам и ожиданиям пользователя, потому что пользователь проходит 11 шагов ввода информации и при попытке вернуться на предыдщуий (нажимает стрелку вверху) теряет все, что вводил. Это очень раздражает. Тогда надо запрос на выход из режима ввода какой-то давать.

**Comment by 4eRTuk** [comment]
Ну как же, вот четко написано - https://developer.android.com/training/implementing-navigation/ancestral.html
Стрелка назад - на уровень назад ( к родителю).

https://developer.android.com/training/implementing-navigation/temporal.html
Кнопка назад - переключение по истории.

**Comment by 4eRTuk** [comment]
запрос может быть стоит, да

**Comment by Kinda-me** [comment]
Да, запроса о сохранении введенных данных очень не хватает.
