### ISSUE TITLE
Последовательность значений на экранах ввода не соответствует последовательности значений в классификаторах

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/tree_mapper#9]
Теряется вся логика, потому что вместа выбора "Здоровое-Ослабленное-Сильно ослабленное..." нужно выбирать из "Ослабленное-Здоровое-Сильно ослабленное...", и так везде.

**Comment by BishopGIS** [comment]
В справочнике порядок правильный - http://176.9.38.120/tree_mapping/resource/5.

**Comment by 4eRTuk** [comment]
А у нас в справочнике нет порядка вообще:
`    "lookup_table": {
        "items": {
            "Здоровое": "Здоровое  (нет внешних повреждений кроны и ствола)", 
            "Ослабленное": "Ослабленное  (наличие усыхающих ветвей, повреждение листьев - до 30%)", 
            "Сильно ослабленное": "Сильно ослабленное (наличие усыхающих ветвей, повреждение листьев  - до 60%)", 
            "Сухостой": "Сухостой (полностью погибшее дерево)", 
            "Отмирающее": "Отмирающее (крона разрушена, более 70% ветвей - сухие)"
        }
    }, `

Нужно в items массив писать, а у нас объект.

**Comment by 4eRTuk** [comment]
Я сделал чтобы порядок добавления в таблицу сохранялся у нас в мобильном, но будет ли JSON гарантировать такой порядок неизвестно.

**Comment by BishopGIS** [comment]
Это уже к серверу вопрос. Пока так оставляем.

**Comment by Kinda-me** [comment]
Вроде все нормально работает теперь, порядок сохраняется.
Только в этом справочнике порядок странный - http://176.9.38.120/tree_mapping/resource/14

**Comment by BishopGIS** [comment]
Это уже вопрос к тому кто и как справочник заполняет. Т.е. на стороне мобильного тут уже ничего не надо делать.
